FROM node:16
WORKDIR /app
COPY --chown=node:node ./package.json ./
RUN rm -rf node_modules/.cache
RUN npm install
COPY --chown=node:node . .
RUN chown -R node:node node_modules/.cache
CMD ["npm", "run", "start"]